services:
  web:
    image: "time-logger"
#    environment:
#        DB_FILE: "../db/time_logger.db"
    volumes:
      - type: bind
        source: ./db
        target: /db
    user: ${CURRENT_UID}
    ports:
      - "8000:8000"
