services:
  web:
    image: "time-logger"
    environment:
        #UVICORN_HOST: "0.0.0.0"
        #UVICORN_PORT: 8000
        #UVICORN_ARGS: ""
        # auth0
        CLIENT_ID: ${CLIENT_ID}
        CLIENT_SECRET: ${CLIENT_SECRET}
        DOMAIN: ${DOMAIN}
        SESSION_SECRET: ${SESSION_SECRET}
    volumes:
      - type: bind
        source: ./db
        target: /db
    user: ${CURRENT_UID}
    ports:
      - "8000:8000"
