name: 'Test Actions'

on:
  workflow_dispatch:
  push:
    branches:
      - main

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: pip install flake8
      
      - name: Run style checks
        run: python3 -m flake8 app/
      
      - name: Run pytest
        run: python3 -m pytest tests/
